use crate::{CoreError,CoreResult,Interval,LineSegment,Point2,Scalar,Segment,Tolerance,clamp_unit,solve_cubic,solve_quadratic};
#[derive(Clone,Copy,Debug,Eq,PartialEq)]pub enum IntersectionKind{Crossing,Tangent,Endpoint}
#[derive(Clone,Copy,Debug,PartialEq)]pub struct PointIntersection{pub point:Point2,pub parameter_a:Scalar,pub parameter_b:Scalar,pub kind:IntersectionKind}
#[derive(Clone,Copy,Debug,PartialEq)]pub struct OverlapIntersection{pub range_a:Interval,pub range_b:Interval}
#[derive(Clone,Copy,Debug,PartialEq)]pub enum Intersection{Point(PointIntersection),Overlap(OverlapIntersection)}
#[derive(Clone,Debug,Default,PartialEq)]pub struct IntersectionResult{pub intersections:Vec<Intersection>}
fn line_line(a:LineSegment,b:LineSegment,tol:Tolerance)->CoreResult<IntersectionResult>{let r=a.end-a.start;let s=b.end-b.start;let denom=r.cross(s);let qp=b.start-a.start;if tol.nearly_zero(denom,r.length()*s.length()){if !tol.nearly_zero(qp.cross(r),qp.length()*r.length()){return Ok(IntersectionResult::default())}let rr=r.dot(r);if rr<=tol.absolute{return Ok(IntersectionResult::default())}let mut t0=qp.dot(r)/rr;let mut t1=(b.end-a.start).dot(r)/rr;if t0>t1{core::mem::swap(&mut t0,&mut t1)}let lo=t0.max(0.0);let hi=t1.min(1.0);if hi<lo-tol.absolute{return Ok(IntersectionResult::default())}if tol.almost_eq(lo,hi){let p=a.point_at(lo);let u=if s.dot(s)==0.0{0.0}else{(p-b.start).dot(s)/s.dot(s)};return Ok(IntersectionResult{intersections:vec![Intersection::Point(PointIntersection{point:p,parameter_a:lo,parameter_b:u,kind:IntersectionKind::Endpoint})]})}let ub0=if s.dot(s)==0.0{0.0}else{(a.point_at(lo)-b.start).dot(s)/s.dot(s)};let ub1=if s.dot(s)==0.0{0.0}else{(a.point_at(hi)-b.start).dot(s)/s.dot(s)};return Ok(IntersectionResult{intersections:vec![Intersection::Overlap(OverlapIntersection{range_a:Interval::new(lo,hi)?,range_b:Interval::new(ub0.min(ub1),ub0.max(ub1))?})]})}let t=qp.cross(s)/denom;let u=qp.cross(r)/denom;let(Some(t),Some(u))=(clamp_unit(t,tol),clamp_unit(u,tol))else{return Ok(IntersectionResult::default())};let kind=if t==0.0||t==1.0||u==0.0||u==1.0{IntersectionKind::Endpoint}else{IntersectionKind::Crossing};Ok(IntersectionResult{intersections:vec![Intersection::Point(PointIntersection{point:a.point_at(t),parameter_a:t,parameter_b:u,kind})]})}
fn line_curve(line:LineSegment,seg:Segment,tol:Tolerance)->CoreResult<IntersectionResult>{let d=line.end-line.start;let mut roots=match seg{Segment::Quadratic(q)=>{let ax=q.p0.x-2.0*q.p1.x+q.p2.x;let ay=q.p0.y-2.0*q.p1.y+q.p2.y;let bx=2.0*(q.p1.x-q.p0.x);let by=2.0*(q.p1.y-q.p0.y);let cx=q.p0.x-line.start.x;let cy=q.p0.y-line.start.y;solve_quadratic(ax*d.y-ay*d.x,bx*d.y-by*d.x,cx*d.y-cy*d.x)},Segment::Cubic(c)=>{let ax=-c.p0.x+3.0*c.p1.x-3.0*c.p2.x+c.p3.x;let ay=-c.p0.y+3.0*c.p1.y-3.0*c.p2.y+c.p3.y;let bx=3.0*c.p0.x-6.0*c.p1.x+3.0*c.p2.x;let by=3.0*c.p0.y-6.0*c.p1.y+3.0*c.p2.y;let cx=-3.0*c.p0.x+3.0*c.p1.x;let cy=-3.0*c.p0.y+3.0*c.p1.y;let ex=c.p0.x-line.start.x;let ey=c.p0.y-line.start.y;solve_cubic(ax*d.y-ay*d.x,bx*d.y-by*d.x,cx*d.y-cy*d.x,ex*d.y-ey*d.x)},Segment::Arc(a)=>{let flat=crate::flatten_path(&{let mut pb=crate::PathBuilder::new();pb.move_to(a.point_at(0.0))?.arc_to(a)?.finish()?},tol)?;let mut out=IntersectionResult::default();for w in flat[0].points.windows(2){let r=line_line(line,LineSegment::new(w[0],w[1]),tol)?;out.intersections.extend(r.intersections);}return Ok(out)},Segment::Line(other)=>return line_line(line,other,tol)};crate::dedup_sorted(&mut roots,tol);let mut out=IntersectionResult::default();for t in roots{let Some(t)=clamp_unit(t,tol)else{continue};let p=seg.point_at(t);let dd=d.dot(d);if dd==0.0{continue}let u=(p-line.start).dot(d)/dd;let Some(u)=clamp_unit(u,tol)else{continue};out.intersections.push(Intersection::Point(PointIntersection{point:p,parameter_a:u,parameter_b:t,kind:if t==0.0||t==1.0||u==0.0||u==1.0{IntersectionKind::Endpoint}else{IntersectionKind::Crossing}}));}Ok(out)}
pub fn intersect_segments(a:Segment,b:Segment,tol:Tolerance)->CoreResult<IntersectionResult>{match(a,b){(Segment::Line(la),Segment::Line(lb))=>line_line(la,lb,tol),(Segment::Line(l),other)=>line_curve(l,other,tol),(other,Segment::Line(l))=>{let mut r=line_curve(l,other,tol)?;for i in &mut r.intersections{if let Intersection::Point(p)=i{core::mem::swap(&mut p.parameter_a,&mut p.parameter_b)}}Ok(r)},_=>Err(CoreError::UnsupportedCase)}}
